# Generated by Django 5.2.2 on 2025-06-08 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_base_price', models.IntegerField()),
                ('distance_additional_price', models.IntegerField()),
                ('time_multiplier_factor', models.FloatField()),
                ('waiting_charge', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.CharField(default=None, max_length=125)),
            ],
        ),
    ]
