# Generated by Django 5.2.2 on 2025-06-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prc_mdl_app', '0002_alter_pricemodel_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemodel',
            name='updated_by',
            field=models.EmailField(default=None, max_length=225, null=True),
        ),
    ]
