# Generated by Django 5.2.2 on 2025-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prc_mdl_app', '0003_alter_pricemodel_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemodel',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
