# Generated by Django 5.2.2 on 2025-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prc_mdl_app', '0004_alter_pricemodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricemodel',
            name='updated_by',
            field=models.EmailField(blank=True, max_length=225, null=True),
        ),
    ]
