# Generated by Django 5.2.2 on 2025-06-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prc_mdl_app', '0005_alter_pricemodel_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceModel',
            new_name='Price',
        ),
    ]
