# Generated by Django 5.2.2 on 2025-06-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prc_mdl_app', '0006_rename_pricemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='created_by',
            field=models.EmailField(default='asus.gmail.com', max_length=225),
        ),
        migrations.AddField(
            model_name='price',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
