# Generated by Django 5.2.2 on 2025-06-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prc_mdl_app', '0007_price_created_by_price_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='created_by',
            field=models.EmailField(max_length=225),
        ),
    ]
