# Generated by Django 5.2.2 on 2025-06-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prc_mdl_app', '0008_alter_price_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
